export const defaultRegionCode = 'SK';

export const regions = [
  { code: 'DZ', name: 'Alžírsko', flag: 'https://flagcdn.com/w320/dz.png' },
  { code: 'AR', name: 'Argentína', flag: 'https://flagcdn.com/w320/ar.png' },
  { code: 'AU', name: 'Austrália', flag: 'https://flagcdn.com/w320/au.png' },
  { code: 'AT', name: 'Rakúsko', flag: 'https://flagcdn.com/w320/at.png' },
  { code: 'AZ', name: 'Azerbajdžan', flag: 'https://flagcdn.com/w320/az.png' },
  { code: 'BH', name: 'Bahrajn', flag: 'https://flagcdn.com/w320/bh.png' },
  { code: 'BD', name: 'Bangladéš', flag: 'https://flagcdn.com/w320/bd.png' },
  { code: 'BY', name: 'Bielorusko', flag: 'https://flagcdn.com/w320/by.png' },
  { code: 'BE', name: 'Belgicko', flag: 'https://flagcdn.com/w320/be.png' },
  { code: 'BO', name: 'Bolívia', flag: 'https://flagcdn.com/w320/bo.png' },
  {
    code: 'BA',
    name: 'Bosna a Hercegovina',
    flag: 'https://flagcdn.com/w320/ba.png',
  },
  { code: 'BR', name: 'Brazília', flag: 'https://flagcdn.com/w320/br.png' },
  { code: 'BG', name: 'Bulharsko', flag: 'https://flagcdn.com/w320/bg.png' },
  { code: 'CA', name: 'Kanada', flag: 'https://flagcdn.com/w320/ca.png' },
  { code: 'CL', name: 'Čile', flag: 'https://flagcdn.com/w320/cl.png' },
  { code: 'CO', name: 'Kolumbia', flag: 'https://flagcdn.com/w320/co.png' },
  { code: 'CR', name: 'Kostarika', flag: 'https://flagcdn.com/w320/cr.png' },
  { code: 'HR', name: 'Chorvátsko', flag: 'https://flagcdn.com/w320/hr.png' },
  { code: 'CY', name: 'Cyprus', flag: 'https://flagcdn.com/w320/cy.png' },
  { code: 'CZ', name: 'Česko', flag: 'https://flagcdn.com/w320/cz.png' },
  { code: 'DK', name: 'Dánsko', flag: 'https://flagcdn.com/w320/dk.png' },
  {
    code: 'DO',
    name: 'Dominikánska republika',
    flag: 'https://flagcdn.com/w320/do.png',
  },
  { code: 'EC', name: 'Ekvádor', flag: 'https://flagcdn.com/w320/ec.png' },
  { code: 'EG', name: 'Egypt', flag: 'https://flagcdn.com/w320/eg.png' },
  { code: 'SV', name: 'Salvádor', flag: 'https://flagcdn.com/w320/sv.png' },
  { code: 'EE', name: 'Estónsko', flag: 'https://flagcdn.com/w320/ee.png' },
  { code: 'FI', name: 'Fínsko', flag: 'https://flagcdn.com/w320/fi.png' },
  { code: 'FR', name: 'Francúzsko', flag: 'https://flagcdn.com/w320/fr.png' },
  { code: 'DE', name: 'Nemecko', flag: 'https://flagcdn.com/w320/de.png' },
  { code: 'GR', name: 'Grécko', flag: 'https://flagcdn.com/w320/gr.png' },
  { code: 'HU', name: 'Maďarsko', flag: 'https://flagcdn.com/w320/hu.png' },
  { code: 'IS', name: 'Island', flag: 'https://flagcdn.com/w320/is.png' },
  { code: 'IN', name: 'India', flag: 'https://flagcdn.com/w320/in.png' },
  { code: 'ID', name: 'Indonézia', flag: 'https://flagcdn.com/w320/id.png' },
  { code: 'IT', name: 'Taliansko', flag: 'https://flagcdn.com/w320/it.png' },
  { code: 'JP', name: 'Japonsko', flag: 'https://flagcdn.com/w320/jp.png' },
  {
    code: 'KR',
    name: 'Kórejská republika',
    flag: 'https://flagcdn.com/w320/kr.png',
  },
  { code: 'LT', name: 'Litva', flag: 'https://flagcdn.com/w320/lt.png' },
  { code: 'LU', name: 'Luxembursko', flag: 'https://flagcdn.com/w320/lu.png' },
  { code: 'MY', name: 'Malajzia', flag: 'https://flagcdn.com/w320/my.png' },
  { code: 'NL', name: 'Holandsko', flag: 'https://flagcdn.com/w320/nl.png' },
  { code: 'NO', name: 'Nórsko', flag: 'https://flagcdn.com/w320/no.png' },
  { code: 'PL', name: 'Poľsko', flag: 'https://flagcdn.com/w320/pl.png' },
  { code: 'PT', name: 'Portugalsko', flag: 'https://flagcdn.com/w320/pt.png' },
  { code: 'SK', name: 'Slovensko', flag: 'https://flagcdn.com/w320/sk.png' },
  { code: 'ES', name: 'Španielsko', flag: 'https://flagcdn.com/w320/es.png' },
  { code: 'SE', name: 'Švédsko', flag: 'https://flagcdn.com/w320/se.png' },
  { code: 'CH', name: 'Švajčiarsko', flag: 'https://flagcdn.com/w320/ch.png' },
  {
    code: 'GB',
    name: 'Spojené kráľovstvo',
    flag: 'https://flagcdn.com/w320/gb.png',
  },
  {
    code: 'US',
    name: 'Spojené štáty',
    flag: 'https://flagcdn.com/w320/us.png',
  },
  { code: 'ZW', name: 'Zimbabwe', flag: 'https://flagcdn.com/w320/zw.png' },
];
