export const regions = [
  { code: 'DZ', name: 'Alžírsko' },
  { code: 'AR', name: 'Argentína' },
  { code: 'AU', name: 'Austrália' },
  { code: 'AT', name: 'Rakúsko' },
  { code: 'AZ', name: 'Azerbajdžan' },
  { code: 'BH', name: 'Bahrajn' },
  { code: 'BD', name: 'Bangladéš' },
  { code: 'BY', name: 'Bielorusko' },
  { code: 'BE', name: 'Belgicko' },
  { code: 'BO', name: 'Bolívia' },
  { code: 'BA', name: 'Bosna a Hercegovina' },
  { code: 'BR', name: 'Brazília' },
  { code: 'BG', name: 'Bulharsko' },
  { code: 'CA', name: 'Kanada' },
  { code: 'CL', name: 'Čile' },
  { code: 'CO', name: 'Kolumbia' },
  { code: 'CR', name: 'Kostarika' },
  { code: 'HR', name: 'Chorvátsko' },
  { code: 'CY', name: 'Cyprus' },
  { code: 'CZ', name: 'Česko' },
  { code: 'DK', name: 'Dánsko' },
  { code: 'DO', name: 'Dominikánska republika' },
  { code: 'EC', name: 'Ekvádor' },
  { code: 'EG', name: 'Egypt' },
  { code: 'SV', name: 'Salvádor' },
  { code: 'EE', name: 'Estónsko' },
  { code: 'FI', name: 'Fínsko' },
  { code: 'FR', name: 'Francúzsko' },
  { code: 'GE', name: 'Gruzínsko' },
  { code: 'DE', name: 'Nemecko' },
  { code: 'GH', name: 'Ghana' },
  { code: 'GR', name: 'Grécko' },
  { code: 'GT', name: 'Guatemala' },
  { code: 'HN', name: 'Honduras' },
  { code: 'HK', name: 'Hongkong' },
  { code: 'HU', name: 'Maďarsko' },
  { code: 'IS', name: 'Island' },
  { code: 'IN', name: 'India' },
  { code: 'ID', name: 'Indonézia' },
  { code: 'IQ', name: 'Irak' },
  { code: 'IE', name: 'Írsko' },
  { code: 'IL', name: 'Izrael' },
  { code: 'IT', name: 'Taliansko' },
  { code: 'JM', name: 'Jamajka' },
  { code: 'JP', name: 'Japonsko' },
  { code: 'JO', name: 'Jordánsko' },
  { code: 'KZ', name: 'Kazachstan' },
  { code: 'KE', name: 'Keňa' },
  { code: 'KR', name: 'Kórejská republika' },
  { code: 'KW', name: 'Kuvajt' },
  { code: 'LV', name: 'Lotyšsko' },
  { code: 'LB', name: 'Libanon' },
  { code: 'LY', name: 'Líbya' },
  { code: 'LT', name: 'Litva' },
  { code: 'LU', name: 'Luxembursko' },
  { code: 'MY', name: 'Malajzia' },
  { code: 'MX', name: 'Mexiko' },
  { code: 'ME', name: 'Čierna Hora' },
  { code: 'MA', name: 'Maroko' },
  { code: 'NP', name: 'Nepál' },
  { code: 'NL', name: 'Holandsko' },
  { code: 'NZ', name: 'Nový Zéland' },
  { code: 'NI', name: 'Nikaragua' },
  { code: 'NG', name: 'Nigéria' },
  { code: 'NO', name: 'Nórsko' },
  { code: 'OM', name: 'Omán' },
  { code: 'PK', name: 'Pakistan' },
  { code: 'PA', name: 'Panama' },
  { code: 'PY', name: 'Paraguaj' },
  { code: 'PE', name: 'Peru' },
  { code: 'PH', name: 'Filipíny' },
  { code: 'PL', name: 'Poľsko' },
  { code: 'PT', name: 'Portugalsko' },
  { code: 'PR', name: 'Portoriko' },
  { code: 'QA', name: 'Katar' },
  { code: 'RO', name: 'Rumunsko' },
  { code: 'RU', name: 'Rusko' },
  { code: 'SA', name: 'Saudská Arábia' },
  { code: 'SN', name: 'Senegal' },
  { code: 'RS', name: 'Srbsko' },
  { code: 'SG', name: 'Singapur' },
  { code: 'SK', name: 'Slovensko' },
  { code: 'SI', name: 'Slovinsko' },
  { code: 'ZA', name: 'Južná Afrika' },
  { code: 'ES', name: 'Španielsko' },
  { code: 'LK', name: 'Srí Lanka' },
  { code: 'SE', name: 'Švédsko' },
  { code: 'CH', name: 'Švajčiarsko' },
  { code: 'TW', name: 'Taiwan' },
  { code: 'TZ', name: 'Tanzánia' },
  { code: 'TH', name: 'Thajsko' },
  { code: 'TN', name: 'Tunisko' },
  { code: 'TR', name: 'Turecko' },
  { code: 'UG', name: 'Uganda' },
  { code: 'UA', name: 'Ukrajina' },
  { code: 'AE', name: 'Spojené arabské emiráty' },
  { code: 'GB', name: 'Spojené kráľovstvo' },
  { code: 'US', name: 'Spojené štáty' },
  { code: 'UY', name: 'Uruguaj' },
  { code: 'VE', name: 'Venezuela' },
  { code: 'VN', name: 'Vietnam' },
  { code: 'YE', name: 'Jemen' },
  { code: 'ZW', name: 'Zimbabwe' },
];
