export const regions = [
  // USA
  { code: 'US', name: 'USA' },

  // Štáty USA
  { code: 'US-AL', name: 'Alabama' },
  { code: 'US-AK', name: 'Aljaška' },
  { code: 'US-AZ', name: 'Arizona' },
  { code: 'US-AR', name: 'Arkansas' },
  { code: 'US-CA', name: 'Kalifornia' },
  { code: 'US-CO', name: 'Colorado' },
  { code: 'US-CT', name: 'Connecticut' },
  { code: 'US-DE', name: 'Delaware' },
  { code: 'US-FL', name: 'Florida' },
  { code: 'US-GA', name: 'Georgia' },
  { code: 'US-HI', name: 'Havaj' },
  { code: 'US-ID', name: 'Idaho' },
  { code: 'US-IL', name: 'Illinois' },
  { code: 'US-IN', name: 'Indiana' },
  { code: 'US-IA', name: 'Iowa' },
  { code: 'US-KS', name: 'Kansas' },
  { code: 'US-KY', name: 'Kentucky' },
  { code: 'US-LA', name: 'Louisiana' },
  { code: 'US-ME', name: 'Maine' },
  { code: 'US-MD', name: 'Maryland' },
  { code: 'US-MA', name: 'Massachusetts' },
  { code: 'US-MI', name: 'Michigan' },
  { code: 'US-MN', name: 'Minnesota' },
  { code: 'US-MS', name: 'Mississippi' },
  { code: 'US-MO', name: 'Missouri' },
  { code: 'US-MT', name: 'Montana' },
  { code: 'US-NE', name: 'Nebraska' },
  { code: 'US-NV', name: 'Nevada' },
  { code: 'US-NH', name: 'New Hampshire' },
  { code: 'US-NJ', name: 'New Jersey' },
  { code: 'US-NM', name: 'Nové Mexiko' },
  { code: 'US-NY', name: 'New York' },
  { code: 'US-NC', name: 'Severná Karolína' },
  { code: 'US-ND', name: 'Severná Dakota' },
  { code: 'US-OH', name: 'Ohio' },
  { code: 'US-OK', name: 'Oklahoma' },
  { code: 'US-OR', name: 'Oregon' },
  { code: 'US-PA', name: 'Pensylvánia' },
  { code: 'US-RI', name: 'Rhode Island' },
  { code: 'US-SC', name: 'Južná Karolína' },
  { code: 'US-SD', name: 'Južná Dakota' },
  { code: 'US-TN', name: 'Tennessee' },
  { code: 'US-TX', name: 'Texas' },
  { code: 'US-UT', name: 'Utah' },
  { code: 'US-VT', name: 'Vermont' },
  { code: 'US-VA', name: 'Virgínia' },
  { code: 'US-WA', name: 'Washington' },
  { code: 'US-WV', name: 'Západná Virgínia' },
  { code: 'US-WI', name: 'Wisconsin' },
  { code: 'US-WY', name: 'Wyoming' },

  // Mexiko
  { code: 'MX', name: 'Mexiko' },

  // Európa
  { code: 'GB', name: 'Veľká Británia' },
  { code: 'SK', name: 'Slovensko' },
  { code: 'CZ', name: 'Česko' },
  { code: 'DE', name: 'Nemecko' },
  { code: 'FR', name: 'Francúzsko' },
  { code: 'IT', name: 'Taliansko' },
  { code: 'ES', name: 'Španielsko' },
  { code: 'PL', name: 'Poľsko' },
  { code: 'HU', name: 'Maďarsko' },
  { code: 'AT', name: 'Rakúsko' },
  { code: 'CH', name: 'Švajčiarsko' },
  { code: 'NL', name: 'Holandsko' },
  { code: 'BE', name: 'Belgicko' },
  { code: 'SE', name: 'Švédsko' },
  { code: 'NO', name: 'Nórsko' },
  { code: 'FI', name: 'Fínsko' },
  { code: 'DK', name: 'Dánsko' },
  { code: 'IE', name: 'Írsko' },
  { code: 'PT', name: 'Portugalsko' },
  { code: 'GR', name: 'Grécko' },
  { code: 'RO', name: 'Rumunsko' },
  { code: 'BG', name: 'Bulharsko' },
  { code: 'HR', name: 'Chorvátsko' },
  { code: 'SI', name: 'Slovinsko' },
  { code: 'LT', name: 'Litva' },
  { code: 'LV', name: 'Lotyšsko' },
  { code: 'EE', name: 'Estónsko' },
  { code: 'CY', name: 'Cyprus' },
  { code: 'LU', name: 'Luxembursko' },
  { code: 'MT', name: 'Malta' },
  { code: 'IS', name: 'Island' },
  { code: 'AL', name: 'Albánsko' },
  { code: 'MK', name: 'Severné Macedónsko' },
  { code: 'RS', name: 'Srbsko' },
  { code: 'BA', name: 'Bosna a Hercegovina' },
  { code: 'ME', name: 'Čierna Hora' },
  { code: 'XK', name: 'Kosovo' },

  // Rusko
  { code: 'RU', name: 'Rusko' },
];
